#!/bin/bash
unzip submissions.zip -d submissions > /dev/null
cd submissions
for FILE in *
do
	# skips student directories
	[[ -d $FILE ]] && continue
	# extracting student name and java file name
	STUDENT_NAME=$(echo "$FILE" | cut -f 1 -d '_')
	FILE_NAME=$(echo "$FILE" | cut -f 4 -d '_')
	# creating student directory if it doesn't exist
	[[ ! -d "$STUDENT_NAME" ]] && mkdir "$STUDENT_NAME"
	#fixing multiple submissions file naming issue - no penalty
	[[ ! -z "$(echo "$FILE_NAME" | grep -E "^.*-.\.java$")" ]] && FILE_NAME=$(echo "$FILE_NAME" | cut -f 1 -d '-').java
	mv "$FILE" "$FILE_NAME"
	#removing package declarations regardless of location - no penalty
	LINE_NUM=$(grep -n "package" "$FILE_NAME" | cut -f 1 -d ":")
	[[ ! -z "$LINE_NUM" ]] && sed -i "${LINE_NUM}d" "$FILE_NAME"
	# placing student's file in their directory
	mv "$FILE_NAME" "$STUDENT_NAME"
done
