#!/bin/bash
echo
echo Compilation Points
javac StaffMember.java Employee.java Hourly.java Payable.java NoOvertimeException.java TestExceptionsV1.java TestExceptionsV2.java
echo
echo Payable Header and Method
cat Payable.java
echo
echo NoOverTimeException Header and Constructor
cat NoOverTimeException.java
echo
echo Normal Execution
`echo ./normal-input` | java TestExceptionsV1
echo
echo Exception Execution
`echo ./exception-input` | java TestExceptionsV1
echo
echo Caught Execution - Message + Continuing + Valid + Average
`echo ./caught-input` | java TestExceptionsV2
echo "SHOULD BE: 2, 47.5 or 23.75"
