#!/bin/bash
cd submissions
for FILE in *
do
	# skips student directories
	[[ -d $FILE ]] && continue
	# extracting student name and java file name
	STUDENT_NAME=$(echo "$FILE" | cut -f 1 -d '_')
	FILE_NAME=$(echo "$FILE" | cut -f 4 -d '_')
	# creating student directory if it doesn't exist
	if [ ! -d "$STUDENT_NAME" ]
	then
		mkdir "$STUDENT_NAME"
	fi
	#fixing multiple submissions file naming issue - no penalty
	[[ ! -z "$(echo "$FILE_NAME" | grep -E "^.*-.\.java$")" ]] && echo "$FILE_NAME" && FILE_NAME=$(echo "$FILE_NAME" | cut -f 1 -d '-').java && echo "$FILE_NAME"
	mv "$FILE" "$FILE_NAME"
	# placing student's file in their directory
	mv "$FILE_NAME" "$STUDENT_NAME"
done
