#!/bin/bash
echo
echo Compilation Points
javac StaffMember.java Employee.java Hourly.java Payable.java NoOvertimeException.java TestExceptionsV1.java TestExceptionsV2.java
echo
echo Payable Header and Method
cat Payable.java
echo
echo NoOverTimeException Header and Constructor
cat NoOverTimeException.java
echo
echo Normal Execution
java TestExceptionsV1
echo
echo Exception Execution
java TestExceptionsV1
echo
echo Caught Execution - Message + Continuing + Valid + Average
java TestExceptionsV2
rm Payable.java Payable.class NoOvertimeException.java NoOvertimeException.class TestExceptionsV1.java TestExceptionsV1.class TestExceptionsV2.java TestExceptionsV2.class
