#!/bin/bash
first=$(head -n 1 Circle.java | cut -c 1-7)
if [ $first == "package" ]; then
	sed -i '1d' Circle.java
fi
javac Circle.java
first=$(head -n 1 CircleTest.java | cut -c 1-7)
if [ $first == "package" ]; then
	sed -i '1d' CircleTest.java
fi
javac CircleTest.java
cat Circle.java
echo
cat CircleTest.java
echo
echo "5" | java CircleTest
echo
echo "100" | java CircleTest
